// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {kiroprocess} from '../models';

export function CreateBackup(arg1:string):Promise<main.Result>;

export function DeleteBackup(arg1:string):Promise<main.Result>;

export function EnsureOriginalBackup():Promise<main.Result>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetBackupList():Promise<Array<main.BackupItem>>;

export function GetCurrentMachineID():Promise<string>;

export function GetKiroProcesses():Promise<Array<kiroprocess.ProcessInfo>>;

export function GetSoftResetStatus():Promise<main.SoftResetStatus>;

export function IsKiroRunning():Promise<boolean>;

export function RepatchExtension():Promise<main.Result>;

export function ResetToNewMachine():Promise<main.Result>;

export function RestoreOriginal():Promise<main.Result>;

export function RestoreSoftReset():Promise<main.Result>;

export function SoftResetToNewMachine():Promise<main.Result>;

export function SwitchToBackup(arg1:string):Promise<main.Result>;

export function UnpatchExtension():Promise<main.Result>;
