// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function EnsureOriginalBackup() {
  return window['go']['main']['App']['EnsureOriginalBackup']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBackupList() {
  return window['go']['main']['App']['GetBackupList']();
}

export function GetCurrentMachineID() {
  return window['go']['main']['App']['GetCurrentMachineID']();
}

export function GetKiroProcesses() {
  return window['go']['main']['App']['GetKiroProcesses']();
}

export function GetSoftResetStatus() {
  return window['go']['main']['App']['GetSoftResetStatus']();
}

export function IsKiroRunning() {
  return window['go']['main']['App']['IsKiroRunning']();
}

export function RepatchExtension() {
  return window['go']['main']['App']['RepatchExtension']();
}

export function ResetToNewMachine() {
  return window['go']['main']['App']['ResetToNewMachine']();
}

export function RestoreOriginal() {
  return window['go']['main']['App']['RestoreOriginal']();
}

export function RestoreSoftReset() {
  return window['go']['main']['App']['RestoreSoftReset']();
}

export function SoftResetToNewMachine() {
  return window['go']['main']['App']['SoftResetToNewMachine']();
}

export function SwitchToBackup(arg1) {
  return window['go']['main']['App']['SwitchToBackup'](arg1);
}

export function UnpatchExtension() {
  return window['go']['main']['App']['UnpatchExtension']();
}
